ci: Add composite action and conditional job execution.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: Formatting, Linting and Testing for OpenTofu Modules
+name: OpenTofu Module CI Pipeline
 
 on:
   push:
@@ -12,7 +12,8 @@ jobs:
   changed-files:
     runs-on: ubuntu-latest
     outputs:
-      files_to_process: ${{ steps.changes.outputs.changed_tf_files }}
+      run_job: ${{ steps.changes.outputs.run_job }}
+      changed_tf_files: ${{ steps.changes.outputs.changed_tf_files }}
     steps:
       - id: checkout_repo
         name: Checkout repository
@@ -21,46 +22,31 @@ jobs:
           fetch-depth: 0
 
       - id: changes
-        name: Get list of changed .tf files
+        name: Get list of changed TF and YAML files
         run: |
-          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.tf')
-          if [ -z "$CHANGED_FILES" ]; then
-            echo "No .tf files have changed"
-            echo "changed_tf_files=" >> "$GITHUB_OUTPUT"
+          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.tf' '*.yml')
+          CHANGED_TF_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.tf')
+          if [ -n "$CHANGED_FILES" ]; then
+            echo "run_job=true" >> "$GITHUB_OUTPUT"
+            echo "changed_tf_files=${CHANGED_TF_FILES}" >> "$GITHUB_OUTPUT"
           else
-            echo "changed_tf_files=${CHANGED_FILES}" >> "$GITHUB_OUTPUT"
+            echo "run_job=false" >> "$GITHUB_OUTPUT"
           fi
 
   tofu-fmt:
     runs-on: ubuntu-latest
     needs: changed-files
+    if: needs.changed-files.outputs.run_job == 'true'
     env:
-      CHANGED_TF_FILES: ${{ needs.changed-files.outputs.files_to_process }}
+      CHANGED_TF_FILES: ${{ needs.changed-files.outputs.changed_tf_files }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Cache OpenTofu .deb package
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/opentofu
-          key: opentofu-${{ env.OPENTOFU_VERSION }}
-          restore-keys: |
-            opentofu-${{ env.OPENTOFU_VERSION }}
-  
       - name: Install OpenTofu
-        run: |
-          if [ ! -f ~/.cache/opentofu/tofu_${OPENTOFU_VERSION}_amd64.deb ]; then
-            echo "Downloading OpenTofu package..."
-            curl -LO https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_VERSION}/tofu_${OPENTOFU_VERSION}_amd64.deb
-            mkdir -p ~/.cache/opentofu
-            mv tofu_${OPENTOFU_VERSION}_amd64.deb ~/.cache/opentofu/
-          fi
-          sudo dpkg -i ~/.cache/opentofu/tofu_${OPENTOFU_VERSION}_amd64.deb
-          sudo apt-get install -f        
-
-      - name: Verify OpenTofu installation
-        run: tofu --version
+        uses: ./.github/actions/tofu-install
+        with:
+          version: ${{ env.OPENTOFU_VERSION }}      
 
       - name: Format changed OpenTofu .tf files
         run: |
@@ -72,14 +58,15 @@ jobs:
               exit 1
             fi
           else
-            echo "No Terraform/OpenTofu files changed in the modules directory."
+            echo "No Terraform/OpenTofu files changed."
           fi
 
   tflint:
     runs-on: ubuntu-latest
     needs: changed-files
+    if: needs.changed-files.outputs.run_job == 'true'
     env:
-      CHANGED_TF_FILES: ${{ needs.changed-files.outputs.files_to_process }}
+      CHANGED_TF_FILES: ${{ needs.changed-files.outputs.changed_tf_files }}
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
       - name: Checkout repository
@@ -105,14 +92,19 @@ jobs:
             for dir in $(echo "$CHANGED_TF_FILES" | xargs -n1 dirname | sort -u); do
               echo "Linting Terraform files in $dir"
               tflint --chdir=$dir --recursive
+              if [ $? -ne 0 ]; then
+                echo "TFLint error found"
+                exit 1
+              fi
             done
           else
-            echo "No Terraform/OpenTofu files changed in the modules directory."
+            echo "No Terraform/OpenTofu files changed."
           fi
   
   bootstrap-test:
-    needs: [tofu-fmt, tflint]
     runs-on: ubuntu-latest
+    needs: [changed-files, tofu-fmt, tflint]
+    if: needs.changed-files.outputs.run_job == 'true'
     environment: sbx
     steps:
       - name: Checkout Repository
@@ -133,8 +125,9 @@ jobs:
           ./bootstrap.sh ${{ vars.ENVIRONMENT }}
 
   test-tofu-plan:
-    needs: bootstrap-test
+    needs: [changed-files, bootstrap-test]
     runs-on: ubuntu-latest
+    if: needs.changed-files.outputs.run_job == 'true'
     environment: sbx
     steps:
       - name: Checkout Repository
@@ -148,27 +141,10 @@ jobs:
           aws-region: ${{ vars.AWS_DEFAULT_REGION }}
           mask-aws-account-id: true
 
-      - name: Cache OpenTofu .deb package
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/opentofu
-          key: opentofu-${{ env.OPENTOFU_VERSION }}
-          restore-keys: |
-            opentofu-${{ env.OPENTOFU_VERSION }}
-  
       - name: Install OpenTofu
-        run: |
-          if [ ! -f ~/.cache/opentofu/tofu_${OPENTOFU_VERSION}_amd64.deb ]; then
-            echo "Downloading OpenTofu package..."
-            curl -LO https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_VERSION}/tofu_${OPENTOFU_VERSION}_amd64.deb
-            mkdir -p ~/.cache/opentofu
-            mv tofu_${OPENTOFU_VERSION}_amd64.deb ~/.cache/opentofu/
-          fi
-          sudo dpkg -i ~/.cache/opentofu/tofu_${OPENTOFU_VERSION}_amd64.deb
-          sudo apt-get install -f        
-
-      - name: Verify OpenTofu installation
-        run: tofu --version
+        uses: ./.github/actions/tofu-install
+        with:
+          version: ${{ env.OPENTOFU_VERSION }}
 
       - name: Tofu Init
         working-directory: examples/sales-spoke-vpc
@@ -180,8 +156,9 @@ jobs:
 
   
   test-tofu-apply:
-    needs: test-tofu-plan
+    needs: [changed-files, test-tofu-plan]
     runs-on: ubuntu-latest
+    if: needs.changed-files.outputs.run_job == 'true'
     environment: sbx-approval
     steps:
       - name: Checkout Repository
@@ -195,27 +172,10 @@ jobs:
           aws-region: ${{ vars.AWS_DEFAULT_REGION }}
           mask-aws-account-id: true
 
-      - name: Cache OpenTofu .deb package
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/opentofu
-          key: opentofu-${{ env.OPENTOFU_VERSION }}
-          restore-keys: |
-            opentofu-${{ env.OPENTOFU_VERSION }}
-  
       - name: Install OpenTofu
-        run: |
-          if [ ! -f ~/.cache/opentofu/tofu_${OPENTOFU_VERSION}_amd64.deb ]; then
-            echo "Downloading OpenTofu package..."
-            curl -LO https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_VERSION}/tofu_${OPENTOFU_VERSION}_amd64.deb
-            mkdir -p ~/.cache/opentofu
-            mv tofu_${OPENTOFU_VERSION}_amd64.deb ~/.cache/opentofu/
-          fi
-          sudo dpkg -i ~/.cache/opentofu/tofu_${OPENTOFU_VERSION}_amd64.deb
-          sudo apt-get install -f        
-
-      - name: Verify OpenTofu installation
-        run: tofu --version
+        uses: ./.github/actions/tofu-install
+        with:
+          version: ${{ env.OPENTOFU_VERSION }}       
 
       - name: Tofu Init
         working-directory: examples/sales-spoke-vpc
@@ -226,8 +186,9 @@ jobs:
         run: tofu apply --var-file="environments/${{ vars.ENVIRONMENT }}/terraform.tfvars" -auto-approve
 
   test-tofu-destroy:
-    needs: test-tofu-apply
+    needs: [changed-files, test-tofu-apply]
     runs-on: ubuntu-latest
+    if: needs.changed-files.outputs.run_job == 'true'
     environment: sbx-approval
     steps:
       - name: Checkout Repository
@@ -241,27 +202,10 @@ jobs:
           aws-region: ${{ vars.AWS_DEFAULT_REGION }}
           mask-aws-account-id: true
 
-      - name: Cache OpenTofu .deb package
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/opentofu
-          key: opentofu-${{ env.OPENTOFU_VERSION }}
-          restore-keys: |
-            opentofu-${{ env.OPENTOFU_VERSION }}
-  
       - name: Install OpenTofu
-        run: |
-          if [ ! -f ~/.cache/opentofu/tofu_${OPENTOFU_VERSION}_amd64.deb ]; then
-            echo "Downloading OpenTofu package..."
-            curl -LO https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_VERSION}/tofu_${OPENTOFU_VERSION}_amd64.deb
-            mkdir -p ~/.cache/opentofu
-            mv tofu_${OPENTOFU_VERSION}_amd64.deb ~/.cache/opentofu/
-          fi
-          sudo dpkg -i ~/.cache/opentofu/tofu_${OPENTOFU_VERSION}_amd64.deb
-          sudo apt-get install -f        
-
-      - name: Verify OpenTofu installation
-        run: tofu --version
+        uses: ./.github/actions/tofu-install
+        with:
+          version: ${{ env.OPENTOFU_VERSION }}        
 
       - name: Tofu Init
         working-directory: examples/sales-spoke-vpc
